### ISSUE TITLE
The checkOut.php needs a front-end !

### ISSUE THREAD

**Issue by lowlevl** [FabLabAvignon/FabPayForm#1]
It's for you @doliG.

You need to make a thanks for paying page.

**Comment by doliG** [comment]
Ok, I'll do it this week.
I'll keep you in touch.

**Comment by lowlevl** [comment]
All details of Api return can be found here -> https://developer.paypal.com/docs/classic/api/merchant/GetExpressCheckoutDetails_API_Operation_NVP/
Also the Api response is returned as a **PHP Array**, named **$checkOutInfos**..
Thanks :D

**Comment by lowlevl** [comment]
Closed with 8189a39 + 97d70e8.
